const headerHTML = `<a class="skip-link" href="#main-content">Skip to main content</a><header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.html" aria-label="ConnectOne Bookkeeping Solutions home"><img class="official-logo header-logo" src="assets/connectone-header-logo-final.png" alt="ConnectOne Bookkeeping Solutions"></a><button class="menu-btn" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="site-navigation">☰</button><nav class="nav" id="site-navigation" aria-label="Primary navigation"><a href="index.html">Home</a><a href="about.html">About</a><a href="services.html">Services</a><a href="industries.html">Industries</a><a href="software.html">Software</a><a href="pricing.html">Pricing</a><a href="faq.html">FAQs</a><a href="contact.html">Contact</a><a class="btn btn-small" href="contact.html#consultation">Book Free Consultation</a></nav></div></header>`;
const footerHTML = `<footer class="footer"><div class="container footer-grid"><div class="footer-brand-column"><a class="brand brand-footer" href="index.html" aria-label="ConnectOne Bookkeeping Solutions home"><img class="official-logo footer-logo" src="assets/connectone-footer-logo-final.png" alt="ConnectOne Bookkeeping Solutions"></a><p>Accurate Today. <b>Stronger Tomorrow.</b></p><p class="muted">Bookkeeping, BAS, payroll and administrative support for Australian businesses.</p></div><div><h4>Quick Links</h4><a href="about.html">About Us</a><a href="services.html">Services</a><a href="industries.html">Industries</a><a href="software.html">Software Support</a><a href="pricing.html">Pricing</a><a href="faq.html">FAQs</a></div><div><h4>Contact</h4><a href="mailto:info@connectonebookkeeping.com.au">info@connectonebookkeeping.com.au</a><a href="tel:+61403893931">Jyotsna: 0403 893 931</a><a href="tel:+61432912115">Viral: 0432 912 115</a><span>Melbourne, Victoria</span></div><div><h4>Legal</h4><a href="privacy.html">Privacy Policy</a><a href="terms.html">Terms & Conditions</a><a href="contact.html">Contact Us</a></div></div><div class="container footer-bottom"><span>© 2026 ConnectOne Bookkeeping Solutions. All Rights Reserved.</span><span>Probity Consultancy Pty Ltd trading as ConnectOne Bookkeeping Solutions</span></div></footer>`;
document.querySelectorAll("[data-header]").forEach(el=>el.outerHTML=headerHTML);
document.querySelectorAll("[data-footer]").forEach(el=>el.outerHTML=footerHTML);
const main=document.querySelector("main"); if(main && !main.id) main.id="main-content";
const current=(location.pathname.split("/").pop()||"index.html");
document.querySelectorAll(".nav a").forEach(a=>{if(a.getAttribute("href")===current)a.classList.add("active")});
const menuBtn=document.querySelector(".menu-btn");
const nav=document.querySelector(".nav");
if(menuBtn&&nav){menuBtn.addEventListener("click",()=>{nav.classList.toggle("open");const open=nav.classList.contains("open");menuBtn.setAttribute("aria-expanded",String(open));menuBtn.textContent=open?"✕":"☰"});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menuBtn.setAttribute("aria-expanded","false");menuBtn.textContent="☰"}));}
if("IntersectionObserver" in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));}else{document.querySelectorAll(".reveal").forEach(el=>el.classList.add("visible"));}
